/**
 * @description       : 
 * @author            : Sorin Ciubotaru BearingPoint GmbH
 * @group             : 
 * @last modified on  : 02-21-2023
 * @last modified by  : Sorin Ciubotaru, BearingPoint GmbH
**/
@IsTest
public with sharing class AdoptionTriggerHandlerTest {
    // public static void testDoTheCheck() {
    //     List<Adoption__c> testExistingRecords = new List<Adoption__c> {
    //         newAdoption__c(Animal__c == '', Account = '')
    //     };

    //     Map<Id, List<Adoption__c>> testExistingRecords = new List<Adoption__> {
    //         'idExample' => new List<Adoption__c> {

    //         }
    //     }
    //     // create test

    //     Test.startTest();

    //     // call the tested method
    //     Test.stopTest();

    //     // verify the results
    // }
}